#!/usr/bin/env sh

if [ -z "$LAZE_PATH" ]
then
  echo "LAZE_PATH environment variable missing"
  exit 1
fi

case $1 in
  electrica)
    cd $LAZE_PATH/gitbot && ./girbot --run=plata_electrica
    break
    ;;
  eon)
    cd $LAZE_PATH/girbot && ./girbot --run=plata_eon
    break
    ;;
  orange)
    cd $LAZE_PATH/girbot && ./girbot --run=plata_orange
    break
    ;;
  upc)
    cd $LAZE_PATH/girbot && ./girbot --run=plata_upc
    break
    ;;
  help)
    cd $LAZE_PATH/girbot && ./girbot
    ;;
  *)
    cd $LAZE_PATH/girbot && ./girbot
    ;;
esac
