#!/usr/bin/env bash

if [ -z "$1" ]
then
  cat << EOF
EOF
  curl -H "Authorization: $TOKEN" -s "http://localhost:3000/" | python -m json.tool
  exit 0
fi

curl -H "Authorization: $TOKEN" -s "http://localhost:3000$*" | python -m json.tool
