#!/usr/bin/env bash

exec 9>/tmp/laze_1_press.lock
if ! flock -n 9  ; then
  echo "another press instance is running";
  exit 1
fi

# Usage:
#   ./press
#   ./press 90 140

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

if [ ! -d "node_modules" ]; then
  node --version
  npm --version
  npm install
fi

node press.js $1 $2
