#!/usr/bin/env bash

exec 9>/tmp/laze_1_press.lock
if ! flock -n 9  ; then
  echo "another press instance is running";
  exit 1
fi

if [ ! -d "node_modules" ]; then
  node --version
  npm --version
  npm install
fi

node press.js $1 $2
