#!/bin/bash

exec 9>/tmp/laze_1_tts.lock
if ! flock -n 9  ; then
  echo "another tts instance is running";
  exit 1
fi

# ./tts ro 100 salutare lume
# ./tts en 50 hello world

say() { mplayer -ao alsa -volume ${2} -noconsolecontrols "http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&q=`echo ${@:3}`&tl=${1}"; }
say $*
